SELECT * FROM  sales_data_sample

--VIEW ORDER QUANTITY, PRICE , SALES AND DEAL SIZE
SELECT QUANTITYORDERED, PRICEEACH, SALES, DEALSIZE
FROM sales_data_sample

---CHANGE DATATYPE FOR  QUANTITYORDERED, PRICEEACH, SALES
ALTER TABLE sales_data_sample
ALTER COLUMN QUANTITYORDERED INT

ALTER TABLE sales_data_sample
ALTER COLUMN PRICEEACH NUMERIC

ALTER TABLE sales_data_sample
ALTER COLUMN SALES NUMERIC

--VIEW TOTAL QUANTITYORDERED , SALES AND PRICE
SELECT SUM(QUANTITYORDERED) AS TOTALORDERS, SUM(PRICEEACH) AS TOTALCOST, SUM(SALES) AS TOTALSALES
FROM  sales_data_sample

--PROFIT %
SELECT SUM(QUANTITYORDERED) AS TOTALORDERS, SUM(PRICEEACH) AS TOTALCOST, SUM(SALES) AS TOTALSALES, (SUM(SALES)-SUM(PRICEEACH)) AS PROFIT
FROM  sales_data_sample;

-- HIGHEST ORDERS CITY VISE
SELECT CITY, COUNT(ORDERNUMBER) AS TOTALORDERS
FROM sales_data_sample
GROUP BY CITY  

-- HIGHEST ORDERS COUNTRY VISE
SELECT COUNTRY, COUNT(ORDERNUMBER) AS TOTALORDERS
FROM sales_data_sample
GROUP BY COUNTRY 


SELECT AVG(SALES) FROM sales_data_sample

-- CUSTOMER NAME WITH MAX SALES
SELECT CUSTOMERNAME, MAX(SALES) AS MAXIMUMSALES
FROM sales_data_sample
GROUP BY CUSTOMERNAME
ORDER BY MAXIMUMSALES DESC

--SALES YEAR WISE
SELECT YEAR_ID, COUNT(QUANTITYORDERED) AS TOTALORDERS
FROM sales_data_sample
GROUP BY YEAR_ID

--orders as per the deal size 
SELECT DEALSIZE , COUNT(QUANTITYORDERED) AS TOTALORDERS
FROM sales_data_sample
GROUP BY DEALSIZE
ORDER BY TOTALORDERS DESC

--PROFIT PERCENTAGE AS PER DEALSIZE
SELECT
    DEALSIZE,
    SUM(SALES) AS TOTAL_SALES,
    SUM(QUANTITYORDERED * PRICEEACH) AS TOTAL_COST,
    ((SUM(SALES) - SUM(QUANTITYORDERED * PRICEEACH)) / SUM(QUANTITYORDERED * PRICEEACH)) * 100 AS PROFIT_PERCENTAGE
FROM
    sales_data_sample
GROUP BY
    DEALSIZE

--TOTAL PROFIT AND SALES
SELECT  SUM(SALES) AS TOTAL_SALES,
    SUM(QUANTITYORDERED * PRICEEACH) AS TOTAL_COST,
    ((SUM(SALES) - SUM(QUANTITYORDERED * PRICEEACH)) / SUM(QUANTITYORDERED * PRICEEACH)) * 100 AS PROFIT_PERCENTAGE, SUM(QUANTITYORDERED) AS TOTALORDERS
	FROM sales_data_sample